server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lilac?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 757520
